### ISSUE TITLE
How to update to my specific layout?

### ISSUE THREAD

**Issue by droidclicketyclacker** [amerharb/ErgoDoxEZ#2]
Greetings, thanks for starting this repo. I was successful in displaying an onscreen keyboard. 

How would I go about in modifying the ascconfig to match my specific layout from the ergodox configurator?

**Comment by amerharb** [comment]
Hi, you can use "Panel Editor" app in macOS.
An easy way to do so is:  goto your onscreen keyboard, click over settings icon on top right, a menu will popup select Customise "ErgoDoxEz Default ....” (in fact I just relize there is a type in panel name Ergo not Erog)  
![image](https://user-images.githubusercontent.com/10150264/83576282-acd76800-a531-11ea-8300-b385fda69f72.png)

**Comment by droidclicketyclacker** [comment]
Thanks for getting back to me. I used the "Customize" panel and tried to update keys using the record button. Even after saving and updating the panel viewer, the keys do not show that i'm pressing them. 

How you you change the "CMD" key for example?

**Comment by amerharb** [comment]
Oh that stuiped record button seems doesn't work, at least with me, what I did: I copy paste buttoms from "Keyboard - ANSI Large” panel you can do it like that:
1. click Add Panel 
<img width="93" alt="image" src="https://user-images.githubusercontent.com/10150264/83775907-cd193b00-a687-11ea-848f-5f5fc9be31f5.png">
2. select Keyboard ANSI - Large
<img width="206" alt="image" src="https://user-images.githubusercontent.com/10150264/83775966-e28e6500-a687-11ea-9529-eb4bf858790b.png">
3. Now you can copy paste buttons from this panel
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/10150264/83776273-46189280-a688-11ea-9c69-70c97e3b73da.png">
